---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-init-container
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
    labelSelector:
      matchLabels:
        jenkins: slave
      matchExpressions:
        - key: jenkins/label
          operator: Exists
        - key: jenkins/label-digest
          operator: Exists
    namespaces:
      - default
  location: "spec.initContainers[name:init]"
  parameters:
    assign:
      value:
        name: init
        imagePullPolicy: IfNotPresent
        image: busybox
        command:
          - /bin/sh
          - -c
          - wget -O /shared/init-jnlp https://raw.githubusercontent.com/zhan9san/init-jnlp/main/init-jnlp
        volumeMounts:
          - name: shared-volume
            mountPath: /shared
